name: Update Contributors
description: Automatically update contributors field of package.json for your repository
author: bubkoo <bubkoo.wy@gmail.com>
inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication.
    required: true

  sort:
    description: Specify if sort contributors by contributions or not. Default `true`.
    required: false
    default: true

  affiliation:
    description: 'Type of collaborators: all/direct/outside.'
    required: false
    default: direct

  include_collaborators:
    description: Should include collaborators or not.
    required: false
    default: true

  include_bots:
    description: Should include bots or not.
    required: false
    default: true

  exclude_users:
    description: Users to exclude.
    required: false

  commit_message:
    description: Commit message of the github action.
    required: false
    default: 'chore: update contributors [skip ci]'

runs:
  using: node16
  main: dist/index.js

branding:
  icon: heart
  color: orange
